name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract
      run: Expand-Archive ngrok.zip

    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Create Tunnel
      run: |
        .\ngrok\ngrok.exe tcp 3389 > log.txt &
        Start-Sleep -Seconds 10
        Invoke-WebRequest -Uri http://127.0.0.1:4040/api/tunnels -OutFile tunnels.json

    - name: Extract Tunnel URL
      run: |
        $json = Get-Content tunnels.json | ConvertFrom-Json
        $url = $json.tunnels[0].public_url
        Set-Content -Path ngrok_url.txt -Value $url

    - name: Commit ngrok_url.txt
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update ngrok URL"
        file_pattern: ngrok_url.txt
