name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

    - name: Extract ngrok
      run: tar -xvzf ngrok.tgz

    - name: Auth with ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install XRDP
      run: |
        sudo apt update
        sudo apt install -y xrdp xfce4 xfce4-goodies
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Set user password
      run: echo "runner:Password123!" | sudo chpasswd

    - name: Start ngrok tunnel for RDP
      run: ./ngrok tcp 3389
